### PR TITLE
Timeline: cliplines is now created

### LINKED ISSUE #258: Timeline | Player Version: Cliplines
When in Player Mode, the timeline should show all filtered clips using _Cliplines._ Each camera with filtered clips should have its own _Clipline_ displayed in the Timline.

A _Clipline_ is a React-component with a list of clips. Each clip should be rendered as a horizontal line, proportional to it's length. The lines should also start proportionally to their start time.

The _Cliplines_ should be expanded vertically, allowing the user to scroll up and down if necessary.

Implement #125 first.

### PR DESCRIPTION
**Pull request by MattiasBeming**
Note: renders all clips, does not render filtered clips. This will be fixed in the future.

Video can play, if one clicks on a clipline, also changes the tab in browser. 

Closes #258

### CODE REVIEW

**Review by eriksellen97 — CHANGES_REQUESTED** [review]
In **cliplines.js**:
Maybe clear comments on lines 16-17, unless you might need them in the future
The methods on line 100 and line 105 should have proper function comment.
The method componentWillMount() on line 100 does not appear to be used/constructed.

In **timeline.js**:
Has the TODO on line 290 been completed?

Otherwise looks very good

**Comment by MattiasBeming** [comment]
The method componentWillMount() in cliplines.js will run before render() each time

**Comment by MattiasBeming** [comment]
componentWillMount() gives a warning. im looking in to this problem at the moment. wait before accepting this pull-request

**Comment by MattiasBeming** [comment]
The warning is fixed. zoom function which updates scale on timeline is now called in the constructor of cliplines.js instead

**Review by eriksellen97 — APPROVED** [review]

**Pull request merged**
