### PR TITLE
feat: filter communication functions

### LINKED ISSUE #128: Communication: Filter Module
Implement action handling for the Filter Module POST-requests.

Complete #139 first.

### PR DESCRIPTION
**Pull request by Kal-Elx**
Closes #128

### CODE REVIEW

**Review by sporreking — CHANGES_REQUESTED** [review]
rebase

**Review by sporreking — CHANGES_REQUESTED** [review]
When using the evoker for `modifyFilter`, the backend crashes. This is due to how the indices explicitly selected for the _whitelisted resolutions_ don't exist in my database. Since this is a test-component, it doesn't matter too much, but should the backend crash since we supplied incorrect indices from frontend? I suggest that the backend checks the supplied data, and returns an error code instead. If you find this unnecessary, just leave a comment and I'll accept anyway.

I also suggest adding a simple test, checking that the `modify_filter` constants in `util.js` are named and exported correctly (such as when checking action constants).

Otherwise, everything looks really good!

**Comment by Kal-Elx** [comment]
I agree that this is undesired behavior but seeing as though #128 is a frontend issue I considered it solved. I'll open a new issue about handling unexpected input in the backend.

I added the tests.

**Review by sporreking — APPROVED** [review]
Sounds good!

**Pull request merged**
